### ISSUE TITLE
[Bug Report] 3.2 start with error

### ISSUE THREAD

**Issue by jarvis1801** [YiWeiHuang-stack/Squirrel-RIFE#531]
2023-09-24 18:20:38,667 - one_line_shot_args - 772 - INFO - Initial New Interpolation Project: project_dir: \output\1, INPUT_FILEPATH: 1.mkv
2023-09-24 18:20:38,668 - one_line_shot_args - 774 - INFO - Changing working dir to 
2023-09-24 18:20:38,668 - one_line_shot_args - 781 - WARNING - Not find selected ffmpeg, use default
Traceback (most recent call last):
File "\one_line_shot_args.py", line 2150, in <module>
File "\one_line_shot_args.py", line 797, in __init__
File "\one_line_shot_args.py", line 240, in __init__
File "\one_line_shot_args.py", line 310, in update_info
File "\one_line_shot_args.py", line 243, in update_frames_info_ffprobe
File "\Utils\utils.py", line 74, in execute
UnicodeDecodeError: 'cp950' codec can't decode byte 0xe3 in position 720: illegal multibyte sequence
INFO - ONE LINE SHOT ARGS 6.6.1 2021/6/26
Warning: Find Empty Args at 'ffmpeg_customized'
Warning: Find Empty Args at 'slow_motion_fps'
Warning: Find Empty Args at 'crop'
Warning: Find Empty Args at 'use_sr_model'

**Comment by Justin62628** [comment]
SVFI 3.2 is not maintained anymore
